### ISSUE TITLE
Not work in windows 11

### ISSUE THREAD

**Issue by jonahfang** [D0BR0MYSL/toggle-tray-icons-win11#1]
![image](https://github.com/D0BR0MYSL/toggle-tray-icons-win11/assets/16301509/e875a0a9-65ba-4384-ab70-45af7f0bb407)

**Comment by KindThinker** [comment]
Hi, sorry for late reply. Thanks for heads up. I think it could be be a codepage incompatibility regional/language settings. I changed codepage to UTF-8 and forced it at script start. Should work now.
